# backend/routers/reports.py — psycopg3 (%s placeholders)
import io, asyncio
from datetime import datetime, date, timedelta
from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor, white
from db.database import get_pool
from middleware.auth import get_current_user

router = APIRouter(prefix='/api/v1/reports', tags=['reports'])
W, H = A4


def _fmt(d) -> str:
    if isinstance(d, (date, datetime)):
        return d.strftime('%d %b %Y')
    return str(d)

def _fmt_time(d) -> str:
    if isinstance(d, datetime):
        return d.strftime('%d %b %Y %I:%M %p')
    return str(d)

def _stat_row(c, label, value, y, color='#111827'):
    c.setFont('Helvetica', 11); c.setFillColor(HexColor('#374151'))
    c.drawString(60, y, label)
    c.setFont('Helvetica-Bold', 11); c.setFillColor(HexColor(color))
    c.drawRightString(545, y, value)
    return y - 20

def _table_row(c, cells, y, is_header=False, stripe=False):
    cols = [55, 200, 370, 460]
    if stripe:
        c.setFillColor(HexColor('#F9FAFB')); c.rect(50, y - 4, 495, 18, fill=1, stroke=0)
    c.setFont('Helvetica-Bold' if is_header else 'Helvetica', 10 if is_header else 9)
    c.setFillColor(HexColor('#111827') if is_header else HexColor('#374151'))
    for i, cell in enumerate(cells):
        c.drawString(cols[i], y, str(cell)[:30])
    if is_header:
        c.setStrokeColor(HexColor('#D1D5DB')); c.line(50, y - 6, 545, y - 6)
    return y - 20


def _build_pdf(user, medicines, doses, from_date, to_date) -> bytes:
    buf    = io.BytesIO()
    c      = canvas.Canvas(buf, pagesize=A4)
    taken  = sum(1 for d in doses if d['status'] == 'taken')
    missed = sum(1 for d in doses if d['status'] == 'missed')
    rate   = round((taken / len(doses)) * 100) if doses else 0

    c.setFillColor(HexColor('#0A7EA4')); c.rect(0, H - 90, W, 90, fill=1, stroke=0)
    c.setFillColor(white); c.setFont('Helvetica-Bold', 26); c.drawString(50, H - 55, 'MediSync')
    c.setFont('Helvetica', 11); c.drawString(50, H - 73, 'Medicine Adherence Report')

    y = H - 110
    c.setFont('Helvetica-Bold', 13); c.setFillColor(HexColor('#111827'))
    c.drawString(50, y, 'Patient Information'); y -= 16
    c.setStrokeColor(HexColor('#E5E7EB')); c.line(50, y, 545, y); y -= 16
    c.setFont('Helvetica', 11); c.setFillColor(HexColor('#374151'))
    for line in [f"Name:   {user['name']}", f"Email:  {user['email']}",
                 f"Period: {_fmt(from_date)} – {_fmt(to_date)}",
                 f"Report generated: {_fmt(datetime.utcnow())}"]:
        c.drawString(50, y, line); y -= 18
    y -= 10

    c.setFont('Helvetica-Bold', 13); c.setFillColor(HexColor('#111827'))
    c.drawString(50, y, 'Adherence Summary'); y -= 16
    c.line(50, y, 545, y); y -= 20
    y = _stat_row(c, 'Total Scheduled Doses', str(len(doses)), y)
    y = _stat_row(c, 'Doses Taken',   str(taken),  y, '#4CAF50')
    y = _stat_row(c, 'Doses Missed',  str(missed), y, '#F44336')
    y = _stat_row(c, 'Adherence Rate', f'{rate}%', y, '#4CAF50' if rate >= 80 else '#FF9800')
    y -= 10

    c.setFont('Helvetica-Bold', 13); c.setFillColor(HexColor('#111827'))
    c.drawString(50, y, 'Medicines'); y -= 16; c.line(50, y, 545, y); y -= 18
    for med in medicines:
        c.setFont('Helvetica-Bold', 11); c.setFillColor(HexColor('#111827'))
        c.drawString(55, y, f"• {med['name']} — {med['dosage']}"); y -= 14
        c.setFont('Helvetica', 10); c.setFillColor(HexColor('#6B7280'))
        c.drawString(65, y, f"Compartment {med['compartment_number']} | {med['food_instruction']} | Stock: {med['quantity']}"); y -= 18
    y -= 10

    if y < 150:
        c.showPage(); y = H - 50
    c.setFont('Helvetica-Bold', 13); c.setFillColor(HexColor('#111827'))
    c.drawString(50, y, 'Dose History'); y -= 16; c.line(50, y, 545, y); y -= 20
    y = _table_row(c, ['Medicine', 'Scheduled', 'Status', 'Taken At'], y, is_header=True)
    for i, dose in enumerate(doses[:50]):
        if y < 60:
            c.showPage(); y = H - 50
        y = _table_row(c, [
            dose['medicine_name'],
            _fmt_time(dose['scheduled_time']),
            dose['status'].upper(),
            _fmt_time(dose['taken_time']) if dose['taken_time'] else '—',
        ], y, stripe=(i % 2 == 0))

    c.setFont('Helvetica', 9); c.setFillColor(HexColor('#9CA3AF'))
    c.drawCentredString(W / 2, 30, 'Generated by MediSync — Smart Medicine Management App')
    c.save(); buf.seek(0)
    return buf.getvalue()


@router.get('/pdf')
async def generate_pdf(
    from_date: str = Query(None, alias='from'),
    to_date:   str = Query(None, alias='to'),
    user: dict = Depends(get_current_user),
):
    pool  = get_pool()
    from_d = datetime.fromisoformat(from_date) if from_date else datetime.utcnow() - timedelta(days=30)
    to_d   = datetime.fromisoformat(to_date)   if to_date   else datetime.utcnow()
    from_d = from_d.replace(hour=0, minute=0, second=0)
    to_d   = to_d.replace(hour=23, minute=59, second=59)

    user_row, meds, doses = await asyncio.gather(
        pool.fetchrow('SELECT * FROM users WHERE id = %s', user['id']),
        pool.fetch('SELECT * FROM medicines WHERE user_id = %s ORDER BY name', user['id']),
        pool.fetch(
            'SELECT * FROM dose_records WHERE user_id=%s AND scheduled_time>=%s AND scheduled_time<=%s ORDER BY scheduled_time',
            user['id'], from_d, to_d,
        ),
    )

    pdf_bytes = _build_pdf(dict(user_row), [dict(m) for m in meds], [dict(d) for d in doses], from_d, to_d)
    filename  = f"MediSync_Report_{from_d.strftime('%Y-%m-%d')}.pdf"
    return StreamingResponse(io.BytesIO(pdf_bytes), media_type='application/pdf',
                             headers={'Content-Disposition': f'attachment; filename="{filename}"'})


@router.get('/summary')
async def get_summary_data(days: int = Query(30), user: dict = Depends(get_current_user)):
    pool = get_pool()
    row  = await pool.fetchrow(
        """SELECT COUNT(*)::int AS total,
                  SUM(CASE WHEN status='taken'  THEN 1 ELSE 0 END)::int AS taken,
                  SUM(CASE WHEN status='missed' THEN 1 ELSE 0 END)::int AS missed
           FROM dose_records
           WHERE user_id=%s AND scheduled_time >= NOW() - (%s || ' days')::INTERVAL""",
        user['id'], str(days),
    )
    r = dict(row)
    return {
        'success': True,
        'data': {'period': days, 'total': r['total'], 'taken': r['taken'], 'missed': r['missed'],
                 'adherenceRate': round((r['taken'] / r['total']) * 100) if r['total'] else 0},
    }
