// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjV5kHZCqBvP5Tx7QID913hxaPQFrpGc8',
    appId: '1:855650668529:web:d9d70ce21b848050823e50',
    messagingSenderId: '855650668529',
    projectId: 'medisync-38574',
    authDomain: 'medisync-38574.firebaseapp.com',
    storageBucket: 'medisync-38574.firebasestorage.app',
    measurementId: 'G-CV1PBQEC74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHEPR6QOM0hbPuNzNzYF0yX6kyPqZ9kNg',
    appId: '1:855650668529:android:a0f3cc48c6e71cb0823e50',
    messagingSenderId: '855650668529',
    projectId: 'medisync-38574',
    storageBucket: 'medisync-38574.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP3LYRqpRm5UifnOu9X1wTEL8FzlXXHcM',
    appId: '1:855650668529:ios:19c1835c19f465ab823e50',
    messagingSenderId: '855650668529',
    projectId: 'medisync-38574',
    storageBucket: 'medisync-38574.firebasestorage.app',
    iosClientId: '855650668529-4mgnbq0tsveqeijieufsvfhq71mbaoti.apps.googleusercontent.com',
    iosBundleId: 'com.medisync.medisync',
  );
}
